// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZjEc8woogszl6xuV6yBTkcw62D7FhpXk',
    appId: '1:257289404993:web:2892043ca3ceaa82983cc0',
    messagingSenderId: '257289404993',
    projectId: 'hello-sugar-web-test',
    authDomain: 'hello-sugar-web-test.firebaseapp.com',
    storageBucket: 'hello-sugar-web-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_gIs5giXBa68Dyb-JgYmzXZ0babRAaZ4',
    appId: '1:257289404993:android:c98fe1a305d60cfa983cc0',
    messagingSenderId: '257289404993',
    projectId: 'hello-sugar-web-test',
    storageBucket: 'hello-sugar-web-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpVjxe6fOofXUI-PJ8pm43MfY2x1U1JKc',
    appId: '1:257289404993:ios:e1460da87f439823983cc0',
    messagingSenderId: '257289404993',
    projectId: 'hello-sugar-web-test',
    storageBucket: 'hello-sugar-web-test.appspot.com',
    iosBundleId: 'com.outcode.hellosugar.helloSugar',
  );
}
